# Generated by Django 6.0.1 on 2026-01-23 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('diet_type', models.CharField(choices=[('all', 'Всеядное'), ('vege', 'Вегетарианское'), ('vegan', 'Веганское'), ('pesca', 'Пескетарианское')], max_length=10)),
                ('calories', models.PositiveIntegerField(verbose_name='Калории')),
                ('protein', models.FloatField(verbose_name='Белки')),
                ('fat', models.FloatField(verbose_name='Жиры')),
                ('carbs', models.FloatField(verbose_name='Углеводы')),
                ('description', models.TextField(verbose_name='Рецепт')),
                ('image_url', models.URLField(default='https://via.placeholder.com/300')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('height', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(230)])),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True)),
                ('goal', models.CharField(max_length=20, null=True)),
                ('activity', models.FloatField(null=True)),
                ('diet_pref', models.CharField(max_length=10, null=True)),
                ('target_kcal', models.IntegerField(blank=True, null=True)),
                ('target_protein', models.IntegerField(blank=True, null=True)),
                ('target_fat', models.IntegerField(blank=True, null=True)),
                ('target_carbs', models.IntegerField(blank=True, null=True)),
                ('refresh_count', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
