# Generated by Django 6.0.1 on 2026-01-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
