# Generated by Django 6.0.1 on 2026-02-06 10:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recipe_meal_type_alter_recipe_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='fans', to='core.recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Премиум подписка'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.FloatField(null=True, verbose_name='Коэфф. активности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(100)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Аллергены'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet_pref',
            field=models.CharField(max_length=10, null=True, verbose_name='Предпочтения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(max_length=20, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(230)], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refresh_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во обновлений'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_kcal',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цель ккал'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(verbose_name='Калории на 100г'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(verbose_name='Углеводы на 100г'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Состав и рецепт'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet_type',
            field=models.CharField(choices=[('all', 'Всеядное'), ('vege', 'Вегетарианское'), ('vegan', 'Веганское'), ('pesca', 'Пескетарианское')], max_length=10, verbose_name='Тип диеты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(verbose_name='Жиры на 100г'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('snack', 'Перекус'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default='lunch', max_length=20, verbose_name='Прием пищи'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(verbose_name='Белки на 100г'),
        ),
    ]
