# Generated by Django 6.0.1 on 2026-02-13 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='refresh_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Почта подтверждена'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_weekly_refresh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее еженедельное обновление'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.FloatField(blank=True, null=True, verbose_name='Коэфф. активности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(110)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diet_pref',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Предпочтения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(250)], verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_carbs',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_fat',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_kcal',
            field=models.IntegerField(default=0, verbose_name='Цель ккал'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_protein',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='Вес'),
        ),
    ]
