# Generated by Django 6.0.1 on 2026-03-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_profile_last_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verification_code',
        ),
    ]
