# Generated by Django 6.0.1 on 2026-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diet_type',
            field=models.CharField(choices=[('all', 'Всеядное'), ('vege', 'Вегетарианское'), ('vegan', 'Веганское'), ('pesca', 'Пескетарианское')], db_index=True, max_length=10, verbose_name='Тип диеты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Завтрак'), ('snack', 'Перекус'), ('lunch', 'Обед'), ('dinner', 'Ужин')], db_index=True, default='lunch', max_length=20, verbose_name='Прием пищи'),
        ),
    ]
